library(dplyr)
install.packages("dplyr")
library(dplyr)
readfile <- read.csv(file='C:/Users/jvanv/R_Analysis/MechaCar_mpg.csv',check.names = F, stringsAsFactors = F)
lm(mpg ~ vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD,readfile)
?lm()
summary(lm(mpg ~ vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD,readfile))

suspensionfile <- read.csv(file='C:/Users/jvanv/R_Analysis/Suspension_Coil.csv',check.names = F, stringsAsFactors = F)
library(tidyverse)
?mutate()
total_summary <- suspensionfile %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI))
lot_summary <- suspensionfile %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups = 'keep')

t.test(suspensionfile$PSI, mu=1500)
?t.test()
t.test(suspensionfile$PSI, mu=1500, subset = 'Lot1')
t.test(suspensionfile$PSI, mu=1500, subset = 'Lot2')
t.test(suspensionfile$PSI, mu=1500, subset = 'Lot3')